### ISSUE TITLE
ReswPlusKeyExtension duplicate on multiple text resource and same namespace

### ISSUE THREAD

**Issue by ray1997** [rudyhuyn/ReswPlus#1]
In my case, I have more than one text resource on my project and put all text resource into my custom namespace "App.Strings".
This issue makes app can't compile because "ReswPlusKeyExtension" is duplicate
Maybe "ReswPlusKeyExtension" enum should be changed if the text resource isn't "Resource" or if there is more than one resw file on the project?
Like "ReswPlusDialogKeyExtension"

**Comment by rudyhuyn** [comment]
Hi Ray1997, thank you for your feedback!

I agree, ReswPlus should definitely support multi resources in the same namespace! We should base the name of the class ReswPlusKeyExtension on the name of the resw file (something we already do for the 2 other auto-generated classes), I will update the project tonight with a new class name generator

**Comment by rudyhuyn** [comment]
Hi @ray1997, I just added support of multi resource files in the same project but also support of resource files in other libraries accessed by binding, markup and code-behind.

Update your visual studio extension and let me know if it fixes your issue!

Rudy

**Comment by ray1997** [comment]
Yep, it works now. Thank you!
